<link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/aos.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/animate.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/meanmenu.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/remixicon.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/odometer.min.css')}}">
<link rel="stylesheet" href="{{asset('')}}assets/css/owl.carousel.min.css">
<link rel="stylesheet" href="{{asset('')}}assets/css/owl.theme.default.min.css">
<link rel="stylesheet" href="{{asset('')}}assets/css/magnific-popup.min.css">
<link rel="stylesheet" href="{{asset('')}}assets/css/fancybox.min.css">
<link rel="stylesheet" href="{{asset('')}}assets/css/nice-select.min.css">
<link rel="stylesheet" href="{{asset('')}}assets/css/style.css">
<link rel="stylesheet" href="{{asset('')}}assets/css/navbar.css">
<link rel="stylesheet" href="{{asset('')}}assets/css/footer.css">
<link rel="stylesheet" href="{{asset('')}}assets/css/dark.css">
<link rel="stylesheet" href="{{asset('')}}assets/css/responsive.css">
